---
abstract: 'Quick::Perl is ...'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Quick-Perl
requires:
  strict: '0'
  warnings: '0'
version: '0.001'
x_authority: cpan:ADAMJS
