---
abstract: 'my kinda/sorta defaults'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Quick-Perl
requires:
  Carp: '0'
  Data::Dumper::Concise: '0'
  Function::Parameters: '0'
  Import::Into: '0'
  Path::Tiny: '0'
  PerlX::Maybe: '0'
  Scalar::Util: '0'
  Set::Tiny: '0'
  Switch::Plain: '0'
  Sys::Info: '0'
  Try::Tiny: '0'
  autobox: '0'
  autobox::Core: '0'
  autodie: '0'
  bareword::filehandles: '0'
  boolean: '0'
  feature: '0'
  indirect: '0'
  match::simple: '0'
  perl: v5.14.0
  strict: '0'
  'true': '0'
  utf8::all: '0'
  warnings: '0'
resources:
  homepage: https://github.com/battlemidget/p5-quick-perl
  repository: https://github.com/battlemidget/p5-quick-perl.git
version: 0.0.4
x_authority: cpan:ADAMJS
